[package]
name = "stew3d"
version = "0.1.0"
edition = "2018"
authors = ["Thomas Castleman <thomascastleman0@gmail.com>"]
description = "A disassembler for the Stew 3000"

[dependencies]
bimap = "0.6.1"
structopt = "0.3.25"